# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SOLEIL_JvQt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.m = QtWidgets.QVBoxLayout()
        self.m.setObjectName("m")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_header = QtWidgets.QHBoxLayout()
        self.logo_header.setObjectName("logo_header")
        self.SOLEIL_logo = QtWidgets.QLabel(self.centralwidget)
        self.SOLEIL_logo.setStyleSheet("background-image: url(:/newPrefix/SOLEIL_logo.png);")
        self.SOLEIL_logo.setText("")
        self.SOLEIL_logo.setPixmap(QtGui.QPixmap("../../../.designer/SOLEIL_logo.png"))
        self.SOLEIL_logo.setScaledContents(True)
        self.SOLEIL_logo.setObjectName("SOLEIL_logo")
        self.logo_header.addWidget(self.SOLEIL_logo)
        self.version_time = QtWidgets.QVBoxLayout()
        self.version_time.setObjectName("version_time")
        self.version_number_label = QtWidgets.QLabel(self.centralwidget)
        self.version_number_label.setMinimumSize(QtCore.QSize(60, 0))
        self.version_number_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_number_label.setObjectName("version_number_label")
        self.version_time.addWidget(self.version_number_label)
        self.current_time_label = QtWidgets.QLabel(self.centralwidget)
        self.current_time_label.setMinimumSize(QtCore.QSize(60, 0))
        self.current_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_time_label.setObjectName("current_time_label")
        self.version_time.addWidget(self.current_time_label)
        self.logo_header.addLayout(self.version_time)
        self.verticalLayout_2.addLayout(self.logo_header)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connection_groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_groupBox.sizePolicy().hasHeightForWidth())
        self.connection_groupBox.setSizePolicy(sizePolicy)
        self.connection_groupBox.setStyleSheet("font: 13pt \".AppleSystemUIFont\";")
        self.connection_groupBox.setObjectName("connection_groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.connection_groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_pixelSwitch = QtWidgets.QCheckBox(self.connection_groupBox)
        self.checkBox_pixelSwitch.setObjectName("checkBox_pixelSwitch")
        self.gridLayout.addWidget(self.checkBox_pixelSwitch, 0, 5, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.connection_groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 4, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(self.connection_groupBox)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout.addWidget(self.pushButton_connect, 1, 4, 1, 1)
        self.label_cntStatus = QtWidgets.QLabel(self.connection_groupBox)
        self.label_cntStatus.setObjectName("label_cntStatus")
        self.gridLayout.addWidget(self.label_cntStatus, 2, 5, 1, 1)
        self.label_timeClickCntBnt = QtWidgets.QLabel(self.connection_groupBox)
        self.label_timeClickCntBnt.setObjectName("label_timeClickCntBnt")
        self.gridLayout.addWidget(self.label_timeClickCntBnt, 1, 5, 1, 1)
        self.lineEdit_srcDelaySec = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_srcDelaySec.setObjectName("lineEdit_srcDelaySec")
        self.gridLayout.addWidget(self.lineEdit_srcDelaySec, 1, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 3, 4, 1, 1)
        self.checkBox_lightShutter = QtWidgets.QCheckBox(self.connection_groupBox)
        self.checkBox_lightShutter.setObjectName("checkBox_lightShutter")
        self.gridLayout.addWidget(self.checkBox_lightShutter, 0, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox_Keithley = QtWidgets.QCheckBox(self.connection_groupBox)
        self.checkBox_Keithley.setObjectName("checkBox_Keithley")
        self.horizontalLayout_3.addWidget(self.checkBox_Keithley)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 4)
        self.lineEdit_cmpl_A = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_cmpl_A.setToolTip("")
        self.lineEdit_cmpl_A.setObjectName("lineEdit_cmpl_A")
        self.gridLayout.addWidget(self.lineEdit_cmpl_A, 2, 1, 1, 1)
        self.lineEdit_meaDelaySec = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_meaDelaySec.setObjectName("lineEdit_meaDelaySec")
        self.gridLayout.addWidget(self.lineEdit_meaDelaySec, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEdit_cmpl_V = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_cmpl_V.setToolTip("")
        self.lineEdit_cmpl_V.setObjectName("lineEdit_cmpl_V")
        self.gridLayout.addWidget(self.lineEdit_cmpl_V, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_shutterCOM = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_shutterCOM.setObjectName("lineEdit_shutterCOM")
        self.gridLayout.addWidget(self.lineEdit_shutterCOM, 3, 3, 1, 1)
        self.lineEdit_keithleyCOM = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_keithleyCOM.setObjectName("lineEdit_keithleyCOM")
        self.gridLayout.addWidget(self.lineEdit_keithleyCOM, 3, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 3, 0, 1, 1)
        self.lineEdit_switchCOM = QtWidgets.QLineEdit(self.connection_groupBox)
        self.lineEdit_switchCOM.setObjectName("lineEdit_switchCOM")
        self.gridLayout.addWidget(self.lineEdit_switchCOM, 3, 5, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.connection_groupBox)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.connection_groupBox)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setStyleSheet("color: rgb(153, 153, 153);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(780, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.smp_groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smp_groupBox.sizePolicy().hasHeightForWidth())
        self.smp_groupBox.setSizePolicy(sizePolicy)
        self.smp_groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.smp_groupBox.setAutoFillBackground(False)
        self.smp_groupBox.setStyleSheet("font: 13pt \".AppleSystemUIFont\";")
        self.smp_groupBox.setObjectName("smp_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.smp_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.smp_groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_filePath = QtWidgets.QLineEdit(self.smp_groupBox)
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.horizontalLayout_2.addWidget(self.lineEdit_filePath)
        self.pushButton_selectDir = QtWidgets.QPushButton(self.smp_groupBox)
        self.pushButton_selectDir.setObjectName("pushButton_selectDir")
        self.horizontalLayout_2.addWidget(self.pushButton_selectDir)
        self.label_24 = QtWidgets.QLabel(self.smp_groupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.lineEdit = QtWidgets.QLineEdit(self.smp_groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.smp_groupBox)
        self.line_2.setStyleSheet("color: rgb(153, 153, 153);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.groupBox = QtWidgets.QGroupBox(self.smp_groupBox)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setStyleSheet("color: rgb(153, 153, 153);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.smp_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.radioButton_pixel2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel2.setObjectName("radioButton_pixel2")
        self.gridLayout_2.addWidget(self.radioButton_pixel2, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 6, 1, 1)
        self.radioButton_pixel3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel3.setObjectName("radioButton_pixel3")
        self.gridLayout_2.addWidget(self.radioButton_pixel3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.lineEdit_pixel1chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel1chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1chem.setObjectName("lineEdit_pixel1chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel1chem, 3, 1, 1, 1)
        self.lineEdit_pixel1cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel1cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1cmt.setObjectName("lineEdit_pixel1cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel1cmt, 6, 1, 1, 1)
        self.lineEdit_pixel6cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel6cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6cmt.setObjectName("lineEdit_pixel6cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel6cmt, 6, 6, 1, 1)
        self.lineEdit_pixel5cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel5cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5cmt.setObjectName("lineEdit_pixel5cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel5cmt, 6, 5, 1, 1)
        self.lineEdit_pixel6chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel6chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6chem.setObjectName("lineEdit_pixel6chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel6chem, 3, 6, 1, 1)
        self.lineEdit_pixel2arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel2arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2arc.setObjectName("lineEdit_pixel2arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel2arc, 4, 2, 1, 1)
        self.lineEdit_pixel5arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel5arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5arc.setObjectName("lineEdit_pixel5arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel5arc, 4, 5, 1, 1)
        self.lineEdit_pixel6arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel6arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6arc.setObjectName("lineEdit_pixel6arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel6arc, 4, 6, 1, 1)
        self.lineEdit_pixel2opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel2opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2opr.setObjectName("lineEdit_pixel2opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel2opr, 5, 2, 1, 1)
        self.lineEdit_pixel3opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel3opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3opr.setObjectName("lineEdit_pixel3opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel3opr, 5, 3, 1, 1)
        self.lineEdit_pixel4opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel4opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4opr.setObjectName("lineEdit_pixel4opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel4opr, 5, 4, 1, 1)
        self.lineEdit_pixel5opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel5opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5opr.setObjectName("lineEdit_pixel5opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel5opr, 5, 5, 1, 1)
        self.lineEdit_pixel6opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel6opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6opr.setObjectName("lineEdit_pixel6opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel6opr, 5, 6, 1, 1)
        self.lineEdit_pixel4cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel4cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4cmt.setObjectName("lineEdit_pixel4cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel4cmt, 6, 4, 1, 1)
        self.lineEdit_pixel3cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel3cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3cmt.setObjectName("lineEdit_pixel3cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel3cmt, 6, 3, 1, 1)
        self.lineEdit_pixel2cmt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel2cmt.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2cmt.setObjectName("lineEdit_pixel2cmt")
        self.gridLayout_2.addWidget(self.lineEdit_pixel2cmt, 6, 2, 1, 1)
        self.lineEdit_pixel2chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel2chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2chem.setObjectName("lineEdit_pixel2chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel2chem, 3, 2, 1, 1)
        self.lineEdit_pixel3chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel3chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3chem.setObjectName("lineEdit_pixel3chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel3chem, 3, 3, 1, 1)
        self.lineEdit_pixel4chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel4chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4chem.setObjectName("lineEdit_pixel4chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel4chem, 3, 4, 1, 1)
        self.lineEdit_pixel5chem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel5chem.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5chem.setObjectName("lineEdit_pixel5chem")
        self.gridLayout_2.addWidget(self.lineEdit_pixel5chem, 3, 5, 1, 1)
        self.lineEdit_pixel3arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel3arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3arc.setObjectName("lineEdit_pixel3arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel3arc, 4, 3, 1, 1)
        self.lineEdit_pixel4arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel4arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4arc.setObjectName("lineEdit_pixel4arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel4arc, 4, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.lineEdit_pixel1arc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel1arc.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1arc.setObjectName("lineEdit_pixel1arc")
        self.gridLayout_2.addWidget(self.lineEdit_pixel1arc, 4, 1, 1, 1)
        self.radioButton_pixel4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel4.setObjectName("radioButton_pixel4")
        self.gridLayout_2.addWidget(self.radioButton_pixel4, 0, 4, 1, 1)
        self.radioButton_pixel6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel6.setObjectName("radioButton_pixel6")
        self.gridLayout_2.addWidget(self.radioButton_pixel6, 0, 6, 1, 1)
        self.radioButton_pixel5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel5.setObjectName("radioButton_pixel5")
        self.gridLayout_2.addWidget(self.radioButton_pixel5, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_pixel1opr = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pixel1opr.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1opr.setObjectName("lineEdit_pixel1opr")
        self.gridLayout_2.addWidget(self.lineEdit_pixel1opr, 5, 1, 1, 1)
        self.radioButton_pixel1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_pixel1.setObjectName("radioButton_pixel1")
        self.gridLayout_2.addWidget(self.radioButton_pixel1, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.smp_groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.smp_groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smp_groupBox_2.sizePolicy().hasHeightForWidth())
        self.smp_groupBox_2.setSizePolicy(sizePolicy)
        self.smp_groupBox_2.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.smp_groupBox_2.setFont(font)
        self.smp_groupBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.smp_groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.smp_groupBox_2.setAutoFillBackground(False)
        self.smp_groupBox_2.setStyleSheet("font: 13pt \".AppleSystemUIFont\";")
        self.smp_groupBox_2.setObjectName("smp_groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.smp_groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_51 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_7.addWidget(self.label_51)
        self.comboBox_singlePixel = QtWidgets.QComboBox(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_singlePixel.sizePolicy().hasHeightForWidth())
        self.comboBox_singlePixel.setSizePolicy(sizePolicy)
        self.comboBox_singlePixel.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_singlePixel.setEditable(False)
        self.comboBox_singlePixel.setModelColumn(0)
        self.comboBox_singlePixel.setObjectName("comboBox_singlePixel")
        self.comboBox_singlePixel.addItem("")
        self.comboBox_singlePixel.addItem("")
        self.comboBox_singlePixel.addItem("")
        self.comboBox_singlePixel.addItem("")
        self.comboBox_singlePixel.addItem("")
        self.comboBox_singlePixel.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_singlePixel)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.label_28 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_27 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_5.addWidget(self.label_27)
        self.lineEdit_filePath_2 = QtWidgets.QLineEdit(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filePath_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_filePath_2.setSizePolicy(sizePolicy)
        self.lineEdit_filePath_2.setObjectName("lineEdit_filePath_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_filePath_2)
        self.label_49 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_5.addWidget(self.label_49)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.label_50 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_5.addWidget(self.label_50)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.label_52 = QtWidgets.QLabel(self.smp_groupBox_2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_5.addWidget(self.label_52)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.smp_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_5.addWidget(self.lineEdit_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addWidget(self.smp_groupBox_2)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setStyleSheet("color: rgb(153, 153, 153);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_pixel1_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel1_2.setObjectName("radioButton_pixel1_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel1_2, 0, 1, 1, 1)
        self.radioButton_pixel6_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel6_2.setObjectName("radioButton_pixel6_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel6_2, 0, 6, 1, 1)
        self.lineEdit_pixel1area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel1area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel1area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel1area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel1area.setObjectName("lineEdit_pixel1area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel1area, 2, 1, 1, 1)
        self.radioButton_pixel4_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel4_2.setObjectName("radioButton_pixel4_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel4_2, 0, 4, 1, 1)
        self.radioButton_pixel5_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel5_2.setObjectName("radioButton_pixel5_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel5_2, 0, 5, 1, 1)
        self.lineEdit_pixel1Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel1Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel1Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel1Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel1Vmin.setObjectName("lineEdit_pixel1Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel1Vmin, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 1, 0, 1, 1)
        self.radioButton_pixel2_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel2_2.setObjectName("radioButton_pixel2_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel2_2, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 0, 1, 1)
        self.lineEdit_pixel1Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel1Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel1Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel1Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel1Vmax.setObjectName("lineEdit_pixel1Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel1Vmax, 4, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 2, 0, 1, 1)
        self.radioButton_pixel3_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pixel3_2.setObjectName("radioButton_pixel3_2")
        self.gridLayout_3.addWidget(self.radioButton_pixel3_2, 0, 3, 1, 1)
        self.lineEdit_pixel6Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel6Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel6Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel6Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel6Vmax.setObjectName("lineEdit_pixel6Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel6Vmax, 4, 6, 1, 1)
        self.lineEdit_pixel5Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel5Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel5Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel5Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel5Vmax.setObjectName("lineEdit_pixel5Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel5Vmax, 4, 5, 1, 1)
        self.lineEdit_pixel2area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel2area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel2area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel2area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel2area.setObjectName("lineEdit_pixel2area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel2area, 2, 2, 1, 1)
        self.lineEdit_pixel3area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel3area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel3area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel3area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel3area.setObjectName("lineEdit_pixel3area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel3area, 2, 3, 1, 1)
        self.lineEdit_pixel4area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel4area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel4area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel4area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel4area.setObjectName("lineEdit_pixel4area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel4area, 2, 4, 1, 1)
        self.lineEdit_pixel5area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel5area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel5area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel5area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel5area.setObjectName("lineEdit_pixel5area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel5area, 2, 5, 1, 1)
        self.lineEdit_pixel6area = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel6area.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel6area.setSizePolicy(sizePolicy)
        self.lineEdit_pixel6area.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6area.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel6area.setObjectName("lineEdit_pixel6area")
        self.gridLayout_3.addWidget(self.lineEdit_pixel6area, 2, 6, 1, 1)
        self.lineEdit_pixel2Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel2Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel2Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel2Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel2Vmin.setObjectName("lineEdit_pixel2Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel2Vmin, 3, 2, 1, 1)
        self.lineEdit_pixel3Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel3Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel3Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel3Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel3Vmin.setObjectName("lineEdit_pixel3Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel3Vmin, 3, 3, 1, 1)
        self.lineEdit_pixel4Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel4Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel4Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel4Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel4Vmin.setObjectName("lineEdit_pixel4Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel4Vmin, 3, 4, 1, 1)
        self.lineEdit_pixel5Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel5Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel5Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel5Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel5Vmin.setObjectName("lineEdit_pixel5Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel5Vmin, 3, 5, 1, 1)
        self.lineEdit_pixel6Vmin = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel6Vmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel6Vmin.setSizePolicy(sizePolicy)
        self.lineEdit_pixel6Vmin.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6Vmin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel6Vmin.setObjectName("lineEdit_pixel6Vmin")
        self.gridLayout_3.addWidget(self.lineEdit_pixel6Vmin, 3, 6, 1, 1)
        self.lineEdit_pixel4Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel4Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel4Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel4Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel4Vmax.setObjectName("lineEdit_pixel4Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel4Vmax, 4, 4, 1, 1)
        self.lineEdit_pixel3Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel3Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel3Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel3Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel3Vmax.setObjectName("lineEdit_pixel3Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel3Vmax, 4, 3, 1, 1)
        self.lineEdit_pixel2Vmax = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel2Vmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel2Vmax.setSizePolicy(sizePolicy)
        self.lineEdit_pixel2Vmax.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2Vmax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel2Vmax.setObjectName("lineEdit_pixel2Vmax")
        self.gridLayout_3.addWidget(self.lineEdit_pixel2Vmax, 4, 2, 1, 1)
        self.comboBox_pixel1 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel1.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel1.setSizePolicy(sizePolicy)
        self.comboBox_pixel1.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel1.setEditable(False)
        self.comboBox_pixel1.setModelColumn(0)
        self.comboBox_pixel1.setObjectName("comboBox_pixel1")
        self.comboBox_pixel1.addItem("")
        self.comboBox_pixel1.addItem("")
        self.comboBox_pixel1.addItem("")
        self.comboBox_pixel1.addItem("")
        self.comboBox_pixel1.addItem("")
        self.comboBox_pixel1.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel1, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 5, 0, 1, 1)
        self.lineEdit_pixel1Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel1Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel1Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel1Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel1Vpts.setObjectName("lineEdit_pixel1Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel1Vpts, 5, 1, 1, 1)
        self.lineEdit_pixel6Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel6Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel6Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel6Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel6Vpts.setObjectName("lineEdit_pixel6Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel6Vpts, 5, 6, 1, 1)
        self.lineEdit_pixel5Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel5Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel5Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel5Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel5Vpts.setObjectName("lineEdit_pixel5Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel5Vpts, 5, 5, 1, 1)
        self.lineEdit_pixel4Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel4Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel4Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel4Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel4Vpts.setObjectName("lineEdit_pixel4Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel4Vpts, 5, 4, 1, 1)
        self.lineEdit_pixel3Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel3Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel3Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel3Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel3Vpts.setObjectName("lineEdit_pixel3Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel3Vpts, 5, 3, 1, 1)
        self.lineEdit_pixel2Vpts = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel2Vpts.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel2Vpts.setSizePolicy(sizePolicy)
        self.lineEdit_pixel2Vpts.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2Vpts.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel2Vpts.setObjectName("lineEdit_pixel2Vpts")
        self.gridLayout_3.addWidget(self.lineEdit_pixel2Vpts, 5, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 6, 0, 1, 1)
        self.lineEdit_pixel1Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel1Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel1Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel1Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel1Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel1Vspo.setObjectName("lineEdit_pixel1Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel1Vspo, 6, 1, 1, 1)
        self.lineEdit_pixel6Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel6Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel6Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel6Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel6Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel6Vspo.setObjectName("lineEdit_pixel6Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel6Vspo, 6, 6, 1, 1)
        self.lineEdit_pixel5Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel5Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel5Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel5Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel5Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel5Vspo.setObjectName("lineEdit_pixel5Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel5Vspo, 6, 5, 1, 1)
        self.lineEdit_pixel4Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel4Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel4Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel4Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel4Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel4Vspo.setObjectName("lineEdit_pixel4Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel4Vspo, 6, 4, 1, 1)
        self.lineEdit_pixel3Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel3Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel3Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel3Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel3Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel3Vspo.setObjectName("lineEdit_pixel3Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel3Vspo, 6, 3, 1, 1)
        self.lineEdit_pixel2Vspo = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pixel2Vspo.sizePolicy().hasHeightForWidth())
        self.lineEdit_pixel2Vspo.setSizePolicy(sizePolicy)
        self.lineEdit_pixel2Vspo.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_pixel2Vspo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_pixel2Vspo.setObjectName("lineEdit_pixel2Vspo")
        self.gridLayout_3.addWidget(self.lineEdit_pixel2Vspo, 6, 2, 1, 1)
        self.comboBox_pixel6 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel6.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel6.setSizePolicy(sizePolicy)
        self.comboBox_pixel6.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel6.setEditable(False)
        self.comboBox_pixel6.setModelColumn(0)
        self.comboBox_pixel6.setObjectName("comboBox_pixel6")
        self.comboBox_pixel6.addItem("")
        self.comboBox_pixel6.addItem("")
        self.comboBox_pixel6.addItem("")
        self.comboBox_pixel6.addItem("")
        self.comboBox_pixel6.addItem("")
        self.comboBox_pixel6.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel6, 1, 6, 1, 1)
        self.comboBox_pixel5 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel5.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel5.setSizePolicy(sizePolicy)
        self.comboBox_pixel5.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel5.setEditable(False)
        self.comboBox_pixel5.setModelColumn(0)
        self.comboBox_pixel5.setObjectName("comboBox_pixel5")
        self.comboBox_pixel5.addItem("")
        self.comboBox_pixel5.addItem("")
        self.comboBox_pixel5.addItem("")
        self.comboBox_pixel5.addItem("")
        self.comboBox_pixel5.addItem("")
        self.comboBox_pixel5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel5, 1, 5, 1, 1)
        self.comboBox_pixel4 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel4.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel4.setSizePolicy(sizePolicy)
        self.comboBox_pixel4.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel4.setEditable(False)
        self.comboBox_pixel4.setModelColumn(0)
        self.comboBox_pixel4.setObjectName("comboBox_pixel4")
        self.comboBox_pixel4.addItem("")
        self.comboBox_pixel4.addItem("")
        self.comboBox_pixel4.addItem("")
        self.comboBox_pixel4.addItem("")
        self.comboBox_pixel4.addItem("")
        self.comboBox_pixel4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel4, 1, 4, 1, 1)
        self.comboBox_pixel3 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel3.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel3.setSizePolicy(sizePolicy)
        self.comboBox_pixel3.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel3.setEditable(False)
        self.comboBox_pixel3.setModelColumn(0)
        self.comboBox_pixel3.setObjectName("comboBox_pixel3")
        self.comboBox_pixel3.addItem("")
        self.comboBox_pixel3.addItem("")
        self.comboBox_pixel3.addItem("")
        self.comboBox_pixel3.addItem("")
        self.comboBox_pixel3.addItem("")
        self.comboBox_pixel3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel3, 1, 3, 1, 1)
        self.comboBox_pixel2 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_pixel2.sizePolicy().hasHeightForWidth())
        self.comboBox_pixel2.setSizePolicy(sizePolicy)
        self.comboBox_pixel2.setMaximumSize(QtCore.QSize(105, 16777215))
        self.comboBox_pixel2.setEditable(False)
        self.comboBox_pixel2.setModelColumn(0)
        self.comboBox_pixel2.setObjectName("comboBox_pixel2")
        self.comboBox_pixel2.addItem("")
        self.comboBox_pixel2.addItem("")
        self.comboBox_pixel2.addItem("")
        self.comboBox_pixel2.addItem("")
        self.comboBox_pixel2.addItem("")
        self.comboBox_pixel2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_pixel2, 1, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_scan = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.horizontalLayout_6.addWidget(self.pushButton_scan)
        self.label_progress = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress.sizePolicy().hasHeightForWidth())
        self.label_progress.setSizePolicy(sizePolicy)
        self.label_progress.setObjectName("label_progress")
        self.horizontalLayout_6.addWidget(self.label_progress)
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 10)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.label_37)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_8.addWidget(self.pushButton_clear)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setStyleSheet("color: rgb(153, 153, 153);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_11.addWidget(self.line_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plottedData_pixel1 = PlotWidget(self.tab_3)
        self.plottedData_pixel1.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel1.setObjectName("plottedData_pixel1")
        self.gridLayout_4.addWidget(self.plottedData_pixel1, 0, 0, 1, 1)
        self.plottedData_pixel2 = PlotWidget(self.tab_3)
        self.plottedData_pixel2.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel2.setObjectName("plottedData_pixel2")
        self.gridLayout_4.addWidget(self.plottedData_pixel2, 0, 1, 1, 1)
        self.plottedData_pixel3 = PlotWidget(self.tab_3)
        self.plottedData_pixel3.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel3.setObjectName("plottedData_pixel3")
        self.gridLayout_4.addWidget(self.plottedData_pixel3, 1, 0, 1, 1)
        self.plottedData_pixel4 = PlotWidget(self.tab_3)
        self.plottedData_pixel4.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel4.setObjectName("plottedData_pixel4")
        self.gridLayout_4.addWidget(self.plottedData_pixel4, 1, 1, 1, 1)
        self.plottedData_pixel5 = PlotWidget(self.tab_3)
        self.plottedData_pixel5.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel5.setObjectName("plottedData_pixel5")
        self.gridLayout_4.addWidget(self.plottedData_pixel5, 2, 0, 1, 1)
        self.plottedData_pixel6 = PlotWidget(self.tab_3)
        self.plottedData_pixel6.setMinimumSize(QtCore.QSize(350, 170))
        self.plottedData_pixel6.setObjectName("plottedData_pixel6")
        self.gridLayout_4.addWidget(self.plottedData_pixel6, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.m.addLayout(self.verticalLayout_2)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.m.addWidget(self.status_label)
        self.statusOutput_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.statusOutput_scrollArea.setMinimumSize(QtCore.QSize(0, 80))
        self.statusOutput_scrollArea.setMaximumSize(QtCore.QSize(16777215, 100))
        self.statusOutput_scrollArea.setWidgetResizable(True)
        self.statusOutput_scrollArea.setObjectName("statusOutput_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.output_window = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.output_window.setText("")
        self.output_window.setObjectName("output_window")
        self.horizontalLayout_9.addWidget(self.output_window)
        self.statusOutput_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.m.addWidget(self.statusOutput_scrollArea)
        self.verticalLayout_6.addLayout(self.m)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_singlePixel.setCurrentIndex(0)
        self.comboBox_pixel1.setCurrentIndex(0)
        self.comboBox_pixel6.setCurrentIndex(0)
        self.comboBox_pixel5.setCurrentIndex(0)
        self.comboBox_pixel4.setCurrentIndex(0)
        self.comboBox_pixel3.setCurrentIndex(0)
        self.comboBox_pixel2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.version_number_label.setText(_translate("MainWindow", "v_1_Dev"))
        self.current_time_label.setText(_translate("MainWindow", "02/02/2020, 20:00"))
        self.connection_groupBox.setTitle(_translate("MainWindow", "Connection:"))
        self.checkBox_pixelSwitch.setText(_translate("MainWindow", "Pixel Switch"))
        self.pushButton_5.setText(_translate("MainWindow", "Shutter On/Off"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.label_cntStatus.setText(_translate("MainWindow", "On / Off"))
        self.label_timeClickCntBnt.setText(_translate("MainWindow", "Connected Time"))
        self.lineEdit_srcDelaySec.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Source delay time (sec)</p></body></html>"))
        self.lineEdit_srcDelaySec.setText(_translate("MainWindow", "0.2"))
        self.label_39.setText(_translate("MainWindow", "Pix Switch COM:"))
        self.checkBox_lightShutter.setText(_translate("MainWindow", "Light Shutter"))
        self.checkBox_Keithley.setText(_translate("MainWindow", "Keithley 2401"))
        self.lineEdit_cmpl_A.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Current compliance (A)</p></body></html>"))
        self.lineEdit_cmpl_A.setText(_translate("MainWindow", "0.002"))
        self.lineEdit_meaDelaySec.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Measurement delay time (sec)</p></body></html>"))
        self.lineEdit_meaDelaySec.setText(_translate("MainWindow", "0.2"))
        self.label_6.setText(_translate("MainWindow", "Cmpl (A):"))
        self.label_7.setText(_translate("MainWindow", "Src Delay (s): "))
        self.lineEdit_cmpl_V.setWhatsThis(_translate("MainWindow", "<html><head/><body><p> Voltage compliance (V)</p></body></html>"))
        self.lineEdit_cmpl_V.setText(_translate("MainWindow", "1.5"))
        self.label_8.setText(_translate("MainWindow", "Mea Delay (s):"))
        self.label_5.setText(_translate("MainWindow", "Cmpl (V):"))
        self.lineEdit_shutterCOM.setText(_translate("MainWindow", "ASRL3::INSTR"))
        self.lineEdit_keithleyCOM.setText(_translate("MainWindow", "GPIB2::20::INSTR"))
        self.label_31.setText(_translate("MainWindow", "Keithley COM:"))
        self.lineEdit_switchCOM.setText(_translate("MainWindow", "ASRL5::INSTR"))
        self.label_38.setText(_translate("MainWindow", "Shutter COM: "))
        self.smp_groupBox.setTitle(_translate("MainWindow", "Saving directory, sample info, checking device connections:"))
        self.label.setText(_translate("MainWindow", "Saving Dir: "))
        self.pushButton_selectDir.setText(_translate("MainWindow", "Select Folder"))
        self.label_24.setText(_translate("MainWindow", "Experiment Name: "))
        self.groupBox.setTitle(_translate("MainWindow", "Sinlge pixel measurement:"))
        self.label_23.setText(_translate("MainWindow", "Device Name:"))
        self.pushButton_3.setText(_translate("MainWindow", "Check Isc (A)"))
        self.label_25.setText(_translate("MainWindow", "0.0015"))
        self.pushButton_4.setText(_translate("MainWindow", "Check Voc (V)"))
        self.label_26.setText(_translate("MainWindow", "1.1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Multi pixel measurement (only when pixel switch is connected):"))
        self.label_10.setText(_translate("MainWindow", "Comments"))
        self.label_2.setText(_translate("MainWindow", "Pixel Number"))
        self.radioButton_pixel2.setText(_translate("MainWindow", "Pixel 2"))
        self.label_19.setText(_translate("MainWindow", "1.1"))
        self.label_16.setText(_translate("MainWindow", "0.0015"))
        self.radioButton_pixel3.setText(_translate("MainWindow", "Pixel 3"))
        self.label_4.setText(_translate("MainWindow", "Architecture"))
        self.label_9.setText(_translate("MainWindow", "Operator"))
        self.label_17.setText(_translate("MainWindow", "1.1"))
        self.radioButton_pixel4.setText(_translate("MainWindow", "Pixel 4"))
        self.radioButton_pixel6.setText(_translate("MainWindow", "Pixel 6"))
        self.radioButton_pixel5.setText(_translate("MainWindow", "Pixel 5"))
        self.label_3.setText(_translate("MainWindow", "Chemistry"))
        self.radioButton_pixel1.setText(_translate("MainWindow", "Pixel 1"))
        self.label_21.setText(_translate("MainWindow", "1.1"))
        self.pushButton.setText(_translate("MainWindow", "Check Isc (A)"))
        self.pushButton_2.setText(_translate("MainWindow", "Check Voc (V)"))
        self.label_22.setText(_translate("MainWindow", "1.1"))
        self.label_20.setText(_translate("MainWindow", "1.1"))
        self.label_11.setText(_translate("MainWindow", "0.0015"))
        self.label_14.setText(_translate("MainWindow", "0.0015"))
        self.label_15.setText(_translate("MainWindow", "0.0015"))
        self.label_18.setText(_translate("MainWindow", "1.1"))
        self.label_12.setText(_translate("MainWindow", "0.0015"))
        self.label_13.setText(_translate("MainWindow", "0.0015"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Initialization"))
        self.smp_groupBox_2.setTitle(_translate("MainWindow", "Scanning Parameters (Single pixel measurement):"))
        self.label_51.setText(_translate("MainWindow", "           Measurement Types:"))
        self.comboBox_singlePixel.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_singlePixel.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_singlePixel.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_singlePixel.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_singlePixel.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_singlePixel.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_singlePixel.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.label_28.setText(_translate("MainWindow", "Aperature Area (cm2):"))
        self.label_27.setText(_translate("MainWindow", "Vmin (V):"))
        self.label_49.setText(_translate("MainWindow", "Vmax (V):"))
        self.label_50.setText(_translate("MainWindow", "# Points:"))
        self.label_52.setText(_translate("MainWindow", "Delta V (mV):"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scanning Parameters (Multi pixel measurement):"))
        self.radioButton_pixel1_2.setText(_translate("MainWindow", "Pixel 1"))
        self.radioButton_pixel6_2.setText(_translate("MainWindow", "Pixel 6"))
        self.radioButton_pixel4_2.setText(_translate("MainWindow", "Pixel 4"))
        self.radioButton_pixel5_2.setText(_translate("MainWindow", "Pixel 5"))
        self.label_32.setText(_translate("MainWindow", "Type of Mea"))
        self.radioButton_pixel2_2.setText(_translate("MainWindow", "Pixel 2"))
        self.label_33.setText(_translate("MainWindow", "Vmax (V)"))
        self.label_34.setText(_translate("MainWindow", "Pixel Number"))
        self.label_35.setText(_translate("MainWindow", "Vmin (V)"))
        self.label_36.setText(_translate("MainWindow", "Area (cm2)"))
        self.radioButton_pixel3_2.setText(_translate("MainWindow", "Pixel 3"))
        self.comboBox_pixel1.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel1.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel1.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel1.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel1.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel1.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel1.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.label_29.setText(_translate("MainWindow", "# Points"))
        self.label_30.setText(_translate("MainWindow", "Vspo (V)"))
        self.comboBox_pixel6.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel6.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel6.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel6.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel6.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel6.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel6.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.comboBox_pixel5.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel5.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel5.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel5.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel5.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel5.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel5.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.comboBox_pixel4.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel4.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel4.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel4.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel4.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel4.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel4.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.comboBox_pixel3.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel3.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel3.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel3.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel3.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel3.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel3.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.comboBox_pixel2.setCurrentText(_translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel2.setItemText(0, _translate("MainWindow", "1. Dark JV (F)"))
        self.comboBox_pixel2.setItemText(1, _translate("MainWindow", "2. Dark JV (R)"))
        self.comboBox_pixel2.setItemText(2, _translate("MainWindow", "3. Sinlge JV (F + R)"))
        self.comboBox_pixel2.setItemText(3, _translate("MainWindow", "4. Single JV (R + F)"))
        self.comboBox_pixel2.setItemText(4, _translate("MainWindow", "5. SPO"))
        self.comboBox_pixel2.setItemText(5, _translate("MainWindow", "6. MPP"))
        self.pushButton_6.setText(_translate("MainWindow", "Update scan parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scanning Setup"))
        self.pushButton_scan.setText(_translate("MainWindow", "Scan"))
        self.label_progress.setText(_translate("MainWindow", "Progress: "))
        self.label_37.setText(_translate("MainWindow", "Clear graph of pixel: "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pixel 1 (Single Pixel Mea)"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Pixel 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Pixel 3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Pixel 4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Pixel 5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Pixel 6"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Data Acquistion "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Data Analysis"))
        self.status_label.setText(_translate("MainWindow", "Status:"))
        self.actionFile.setText(_translate("MainWindow", "File"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

